name: first
'on': push
jobs:
  depends:
    needs: [ubuntu,windows,macos]
    runs-on: ubuntu-latest
    steps:
      run: date
  macos:
    run-on: macos-latest
    steps:
      run: date
  ubuntu:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      run: date
  windows:
    runs-on: windows-latest
    steps:
      run: date
