name: first

on: push

jobs:
    ubuntu:
      name: First Job
      runs-on: ubuntu-latest
      steps:
            run: date
    windows:
      runs-on: windows-latest
      steps:
        run: date
    macos:
      run-on: macos-latest
      steps:
        run: date
    depends:
      runs-on: ubuntu-latest
      needs : [ubuntu,windows,macos]
      steps:
        run: date